/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artion_androiddemos_utils_JniUtils */

#ifndef _Included_com_artion_androiddemos_utils_JniUtils
#define _Included_com_artion_androiddemos_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artion_androiddemos_utils_JniUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artion_androiddemos_utils_JniUtils_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
